[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_amm = "4aSaHMyUotGJULhGimrZf25prAFpKPd2G56pCGedXoNm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kiem.tran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
